# oz-next-app/wrangler.toml

name = "oz-next-app"
main = ".open-next/worker.js"
compatibility_date = "2026-09-01"
compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public",
]

workers_dev = false
preview_urls = false
upload_source_maps = true
keep_names = false

[[routes]]
pattern = "erp.ozotecev.com/*"
zone_name = "ozotecev.com"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[images]
binding = "IMAGES"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "oz-next-app"

[[services]]
binding = "ERP_EDGE"
service = "oz-erp-edge"

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1.0

[observability.traces]
enabled = true

[vars]
NEXTJS_ENV = "production"

NEXT_PUBLIC_APP_ENV = "production"
NEXT_PUBLIC_APP_ORIGIN = "https://erp.ozotecev.com"
NEXT_PUBLIC_API_BASE_URL = "https://api.erp.ozotecev.com"
NEXT_PUBLIC_AUTH_CLIENT_ID = "erp-web"
NEXT_PUBLIC_APP_VERSION = "0.22.0"
NEXT_PUBLIC_LOG_LEVEL = "warn"