# oz-next-app/wrangler.toml

name = "oz-next-app"
main = ".open-next/worker.js"
compatibility_date = "2026-07-09"
compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public",
]

workers_dev = false
preview_urls = false
upload_source_maps = true

[[routes]]
pattern = "erp.ozotecev.com/*"
zone_name = "ozotecev.com"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[images]
binding = "IMAGES"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "oz-next-app"

[placement]
region = "gcp:asia-south1"

[observability]
enabled = true
head_sampling_rate = 0.1

[vars]
NEXTJS_ENV = "production"

NEXT_PUBLIC_APP_ENV = "production"
NEXT_PUBLIC_APP_ORIGIN = "https://erp.ozotecev.com"
NEXT_PUBLIC_API_BASE_URL = "https://api.erp.ozotecev.com"
NEXT_PUBLIC_AUTH_CLIENT_ID = "erp-web"
NEXT_PUBLIC_APP_VERSION = "0.1.0"
NEXT_PUBLIC_LOG_LEVEL = "warn"